name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: thevenin Version
      description: What version of thevenin are you running?
      placeholder: thevenin version
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of python are you using?
      placeholder: python version
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Provide clear steps to reproduce the bug. Ideally, include a code block
        that demonstrates the issue. Aim for a minimal, easy-to-understand example
        by simplifying or removing unnecessary parts of your code. Only include
        code leading up to where the error occurs—for instance, if the error is
        thrown on line 30, do not include any lines after that.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Copy and paste any relevant log output. Your log will automatically be
        formatted into code, so there is no need for backticks.
      render: shell